services:
  - type: web
    name: solace-chatbot-api
    runtime: python
    pythonVersion: "3.11"
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MISTRAL_API_KEY
        sync: false
      - key: HF_TOKEN
        sync: false
      - key: HF_REPO_ID
        sync: false
